export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const ADD_CONTACT = 'ADD_CONTACT';

export const EDIT_CONTACT = 'EDIT_CONTACT';

export const DELETE_CONTACT = 'DELETE_CONTACT';